### ISSUE TITLE
Remove the npm reveal.js dependency and add a vendored download of reveal.js

### ISSUE THREAD

**Issue by infernocloud** [openwichita/lake-afton-interactive-exhibits#17]
Update all existing presentations with the new location of reveal.js

**Comment by infernocloud** [comment]
Hey Wilson, thank you for contributing! Unfortunately the Lake Afton Public Observatory does not currently have internet access available. We're running this whole repo locally. So we can not use the CDN version of reveal.js.

I had to revert your previously merged pull request. Would you be able to include the latest minified reveal.js in the project directly in a vendored folder and update the existing presentations again?

**Comment by nisrulz** [comment]
if this is still open can i work on this ?

**Comment by DJSethDuncan** [comment]
Absolutely! That'd be great.

**Comment by nisrulz** [comment]
PR #21  fixes the issue.

**Comment by nisrulz** [comment]
I have pushed another PR #24 after our discussion on PR #21 .

**Comment by doshitan** [comment]
#24 was merged and resolved this.
